apiVersion: v1
kind: ConfigMap
metadata:
  name: write-api-config
data:
  SERVICE_NAME: "write-api"
  SPANNER_DB: "projects/url-shortener/instances/main/databases/urls"
  SPANNER_EMULATOR_HOST: "spanner-emulator:9010"
  REDIS_ADDR: "redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  SHORT_LINK_BASE_URL: "http://localhost:10001"
