plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'   // JdbcTemplate for block reservation
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.postgresql:postgresql'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'

    // etcd Java client — worker-ID registry for Snowflake strategy
    implementation 'io.etcd:jetcd-core:0.7.7'
}

bootRun {
    jvmArgs = ['-Dserver.port=8085']
}
