plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.kafka:spring-kafka'

    // Debezium embedded engine + PostgreSQL connector
    implementation 'io.debezium:debezium-api:2.6.2.Final'
    implementation 'io.debezium:debezium-embedded:2.6.2.Final'
    implementation 'io.debezium:debezium-connector-postgres:2.6.2.Final'

    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
}
